# Site settings
title: "Nick Guletskii's blog"
email: nickguletskii200@gmail.com
description: "Programming, Linux and other things"
baseurl: ""
url: "http://nickguletskii.github.io"

# Build settings
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"

paginate: 10
paginate_path: "/blog/page:num"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: "blog"
      type: "post"
    values:
      layout: "post"
      author: "Nick Guletskii"